version: '3'

services:

  nginx:
    container_name: ieducar-nginx
    build: docker/nginx
    links:
      - php
    ports:
      - 80
    working_dir: /application
    volumes:
      - ./:/application

  php:
    container_name: ieducar-php
    build: docker/php
    links:
      - redis
    environment:
      CORE_EXT_CONFIGURATION_ENV: development
      XDEBUG_IDEKEY: VSCODE
      XDEBUG_REMOTE_HOST: 192.168.100.5
      XDEBUG_REMOTE_PORT: 9000
      XDEBUG_REMOTE_ENABLE: 1
    working_dir: /application
    volumes:
      - ./:/application

  redis:
    container_name: ieducar-redis
    image: redis
    restart: always
    ports:
      - 6379
