INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Almiro Sartori, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Arnaldo Busatto, C E Dr-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Ayrton Senna da Silva, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Bartolomeu Mitre, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Carima, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Carlos Drummond de Andrade, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Carmelita S Dias, C E Profa-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Castelo Branco, C E Pres-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Cataratas do Iguacu, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Ceebja Helena Kolody-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Ceebja Prof Orides B Guerra-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Centro Est Educ Profis Manoel M Pena', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Costa E Silva, C E Pres-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Flavio Warken, C E Prof-Ef M Prof', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Guilherme, C E Mons-Ef M Prof', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Gustavo D da Silva, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Ipe Roxo, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Jorge Schimmelpfeng, C E-Ef M P', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Juscelino K de Oliveira, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Mariano C Paganoto, C E Prof-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Paulo Freire, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Pedro Ii, C E Dom-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Pioneiros, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Rio Branco, C E Bar Do-Ef M N Prof', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Santa Rita, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Sol de Maio, C E-Ef M Prof', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Tamandare, C E Alm-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Tancredo de A Neves, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Tarquinio Santos, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Tres Fronteiras, C E-Ef M', 4031);
INSERT INTO public.escola_municipio (nome, ref_idmun) VALUES ('Ulysses Guimaraes, C E-Ef M Prof', 4031);
